// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sevval.Persistence.Context;

#nullable disable

namespace Sevval.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251008180527_Yenilanmodel2")]
    partial class Yenilanmodel2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("KurumsalRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Document1Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Document2Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KurumsalRegisters");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderFullName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sevval.Domain.Entities.AfisTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IlanTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsimSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfisTalepler");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcikAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultantCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IlanSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsActive")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsultant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsSubscribed")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level5CertificatePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referans")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxPlatePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ucretlilik")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantCompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Sevval.Domain.Entities.BireyselIlanTakibi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Balkon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BinaKatSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BinaYasi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BulunduguKat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CepTel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlanFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlanGirildiMi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlanNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isim")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsitmaSistemi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .HasColumnType("TEXT");

                    b.Property<string>("MahalleKoy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metrekare")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OdaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parsel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referans")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tapu")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BireyselIlanTakipleri");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.Common.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.ConsultantInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("InvitationToken")
                        .IsUnique();

                    b.HasIndex("InvitedBy");

                    b.ToTable("ConsultantInvitations");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.Country", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("lower(substr(hex(randomblob(16)), 1, 8) || '-' ||    substr(hex(randomblob(16)), 9, 4) || '-' ||    substr(hex(randomblob(16)), 13, 4) || '-' ||    substr(hex(randomblob(16)), 17, 4) || '-' ||    substr(hex(randomblob(16)), 21, 12)  )");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Boundry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("lower(substr(hex(randomblob(16)), 1, 8) || '-' ||    substr(hex(randomblob(16)), 9, 4) || '-' ||    substr(hex(randomblob(16)), 13, 4) || '-' ||    substr(hex(randomblob(16)), 17, 4) || '-' ||    substr(hex(randomblob(16)), 21, 12)  )");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.ForgettenPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("lower(substr(hex(randomblob(16)), 1, 8) || '-' ||    substr(hex(randomblob(16)), 9, 4) || '-' ||    substr(hex(randomblob(16)), 13, 4) || '-' ||    substr(hex(randomblob(16)), 17, 4) || '-' ||    substr(hex(randomblob(16)), 21, 12)  )");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ForgettenPasswords");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.GununIlanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcikAlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdaNo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Aidat")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AramaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("AraziNiteliği")
                        .HasColumnType("TEXT");

                    b.Property<double>("Area")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<string>("ArsaDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asansor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Balkon")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanyoSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BinaYasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrutMetrekare")
                        .HasColumnType("TEXT");

                    b.Property<string>("BulunduguKat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Esyali")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gabari")
                        .HasColumnType("TEXT");

                    b.Property<string>("GayrimenkulSahibi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GoruntulenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("GunlukMusteriSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlanNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImarDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isitma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kaks")
                        .HasColumnType("TEXT");

                    b.Property<string>("KapaliAlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("KatSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kimden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konum")
                        .HasColumnType("TEXT");

                    b.Property<string>("KonutDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("KrediyeUygunluk")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullanimDurumu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<int>("MesajSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeyveninCinsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MulkTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MulkTipiArsa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetMetrekare")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdaSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Otopark")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaftaNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParselNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatronunNotu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCategories")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerhDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TKGMParselLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Takas")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakasaUygunluk")
                        .HasColumnType("TEXT");

                    b.Property<string>("TapuDurumu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasınmazNumarasi")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("TelefonAramaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("YatakSayisi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YayinlanmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("mahalleKoy")
                        .HasColumnType("TEXT");

                    b.Property<string>("sehir")
                        .HasColumnType("TEXT");

                    b.Property<string>("semt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GununIlanlari");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.GununIlaniTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcikAlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdaNo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Aidat")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AramaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("AraziNiteliği")
                        .HasColumnType("TEXT");

                    b.Property<double>("Area")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<string>("ArsaDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asansor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Balkon")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanyoSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BinaYasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrutMetrekare")
                        .HasColumnType("TEXT");

                    b.Property<string>("BulunduguKat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Esyali")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gabari")
                        .HasColumnType("TEXT");

                    b.Property<string>("GayrimenkulSahibi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GoruntulenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("GunlukMusteriSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlanNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImarDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isitma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kaks")
                        .HasColumnType("TEXT");

                    b.Property<string>("KapaliAlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("KatSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kimden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konum")
                        .HasColumnType("TEXT");

                    b.Property<string>("KonutDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("KrediyeUygunluk")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullanimDurumu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<int>("MesajSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeyveninCinsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MulkTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MulkTipiArsa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetMetrekare")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdaSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Otopark")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaftaNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParselNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatronunNotu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCategories")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerhDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TKGMParselLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Takas")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakasaUygunluk")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TapuDurumu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasınmazNumarasi")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("TelefonAramaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("YatakSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("mahalleKoy")
                        .HasColumnType("TEXT");

                    b.Property<string>("sehir")
                        .HasColumnType("TEXT");

                    b.Property<string>("semt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GununIlaniTalepler");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.HaftalikArama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carsamba")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cumartesi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pazar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pazartesi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Persembe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sali")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Toplam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HaftalikAramalar");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.HaftalikBegeniler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carsamba")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cumartesi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pazar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pazartesi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Persembe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sali")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Toplam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HaftalikBegeniler");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.HaftalikGoruntulenme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carsamba")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cumartesi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pazar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pazartesi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Persembe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sali")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Toplam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HaftalikGoruntulenmeler");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.IlanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcikAlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdaNo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Aidat")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Altyapi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AramaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("AraziNiteliği")
                        .HasColumnType("TEXT");

                    b.Property<double>("Area")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<string>("ArsaDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asansor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Balkon")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanyoSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BinaYasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrutMetrekare")
                        .HasColumnType("TEXT");

                    b.Property<string>("BulunduguKat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cephe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisOzellikler")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngelliVeYasliUygunluk")
                        .HasColumnType("TEXT");

                    b.Property<string>("Esyali")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gabari")
                        .HasColumnType("TEXT");

                    b.Property<string>("GayrimenkulSahibi")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenelOzellikler")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GoruntulenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("GunlukMusteriSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcOzellikler")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlanNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImarDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isitma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kaks")
                        .HasColumnType("TEXT");

                    b.Property<string>("KapaliAlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("KatSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kimden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konum")
                        .HasColumnType("TEXT");

                    b.Property<string>("KonumOzellikleri")
                        .HasColumnType("TEXT");

                    b.Property<string>("KonutDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("KonutTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KrediyeUygunluk")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullanimDurumu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 3)
                        .HasColumnType("REAL");

                    b.Property<string>("Manzara")
                        .HasColumnType("TEXT");

                    b.Property<int>("MesajSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeyveninCinsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Muhit")
                        .HasColumnType("TEXT");

                    b.Property<string>("MulkTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MulkTipiArsa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetMetrekare")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdaSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Otopark")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaftaNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParselNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatronunNotu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCategories")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerhDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TKGMParselLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Takas")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakasaUygunluk")
                        .HasColumnType("TEXT");

                    b.Property<string>("TapuDurumu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasınmazNumarasi")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("TelefonAramaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ulasim")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("YatakSayisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("mahalleKoy")
                        .HasColumnType("TEXT");

                    b.Property<string>("sehir")
                        .HasColumnType("TEXT");

                    b.Property<string>("semt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IlanBilgileri", (string)null);
                });

            modelBuilder.Entity("Sevval.Domain.Entities.MembershipChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level5CertificatePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MembershipChangeRequests");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.PhotoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.RecentlyVisitedAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Property")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("UserId");

                    b.ToTable("RecentlyVisitedAnnouncements");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Sevval.Domain.Entities.SatisTalep", b =>
                {
                    b.Property<int?>("RequestNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bathrooms")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingAge")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistanceToSettlement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Floor")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterestedPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandAda")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandParsel")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("LandVillage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LivingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxBudget")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinBudget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parking")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentialCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentialDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentialVillage")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoadCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rooms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slope")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoningStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("selectCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("selectStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestNumber");

                    b.ToTable("SatisTalepleri");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sepet");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.SmsSendHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SmsSendHistory");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.TempEstateVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("lower(substr(hex(randomblob(16)), 1, 8) || '-' ||    substr(hex(randomblob(16)), 9, 4) || '-' ||    substr(hex(randomblob(16)), 13, 4) || '-' ||    substr(hex(randomblob(16)), 17, 4) || '-' ||    substr(hex(randomblob(16)), 21, 12)  )");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TempEstateVerifications");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("lower(substr(hex(randomblob(16)), 1, 8) || '-' ||    substr(hex(randomblob(16)), 9, 4) || '-' ||    substr(hex(randomblob(16)), 13, 4) || '-' ||    substr(hex(randomblob(16)), 17, 4) || '-' ||    substr(hex(randomblob(16)), 21, 12)  )");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.UserVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizedPropertyNumbers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerificationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerificationExpiryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserVerifications");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.VideoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VisitTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.VisitorCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveVisitors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalVisitors")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VisitorCounts");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.YorumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yorum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("Sevval.Persistence.Context.sevvalemlak.Models.AboutUsContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AboutUsContents");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideoLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLike")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoLikes");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideoYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentYorumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentYorumId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoYorumlari");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideolarSayfasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BegeniSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DislikeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsYouTube")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KapakFotografiYolu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoAciklamasi")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YukleyenKullaniciId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("YukleyenKullaniciId");

                    b.ToTable("VideolarSayfasi");
                });

            modelBuilder.Entity("YourProjectName.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sevval.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "ConsultantCompany")
                        .WithMany("Consultants")
                        .HasForeignKey("ConsultantCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConsultantCompany");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.ConsultantInvitation", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sevval.Domain.Entities.ForgettenPassword", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.MembershipChangeRequest", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.RecentlyVisitedAnnouncement", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.IlanModel", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.UserVerification", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.YorumModel", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.IlanModel", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Ilan");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideoLike", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sevval.Web.Models.VideolarSayfasi", "Video")
                        .WithMany("LikesDislikes")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideoYorum", b =>
                {
                    b.HasOne("Sevval.Web.Models.VideoYorum", "ParentYorum")
                        .WithMany("Yanitlar")
                        .HasForeignKey("ParentYorumId");

                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "Kullanici")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sevval.Web.Models.VideolarSayfasi", "Video")
                        .WithMany("Yorumlar")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("ParentYorum");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideolarSayfasi", b =>
                {
                    b.HasOne("Sevval.Domain.Entities.ApplicationUser", "YukleyenKullanici")
                        .WithMany()
                        .HasForeignKey("YukleyenKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YukleyenKullanici");
                });

            modelBuilder.Entity("Sevval.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Consultants");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideoYorum", b =>
                {
                    b.Navigation("Yanitlar");
                });

            modelBuilder.Entity("Sevval.Web.Models.VideolarSayfasi", b =>
                {
                    b.Navigation("LikesDislikes");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
